Add ignore argument, update actions
circuitpython/circuitpython-unified-build-ci pull request #35
Opened 2024-02-12 18:01 UTC by tekktrik

- Adds ignore argument for ignoring specific bundles
- Updates actions to use Node 20
- Stops dumping the GitHub context, which I believe I read somewhere wasn't advised

2024-02-12 21:44 UTC, jepler commented
What is the motivation for the change? I think I missed seeing context.

Does the release-gh step need the same treatment?

2024-02-12 22:10 UTC, tekktrik commented
No, this actually brings that functionality already in the `release-gh` action to the `build` action.  The motivation is issues like https://github.com/adafruit/Adafruit_CircuitPython_Typing/issues/36.

2024-02-13 01:45 UTC, jepler commented
Thanks for the clarification!

2024-02-13 01:46 UTC, jepler submitted a review, later dismissed
Lgtm but don't know how to test

2024-02-13 05:01 UTC, dhalbert requested changes

2024-02-13 05:01 UTC, dhalbert commented on .github/workflows/build.yml
>          submodules: true
This is a new setting that will suppress progress-bar-style output, which mostly just many lines to the logs. I made this change on other repos that I updated to `actions/checkout@v4`.
```suggestion
        submodules: true
        show-progress: false
```

2024-02-13 05:01 UTC, dhalbert commented on build/action.yml
>        submodules: true
```suggestion
      submodules: true
      show-progress: false
```

2024-02-13 05:01 UTC, dhalbert commented on build/action.yml
>        repository: adafruit/actions-ci-circuitpython-libs
```suggestion
      show-progress: false
      repository: adafruit/actions-ci-circuitpython-libs
```

2024-02-13 05:01 UTC, dhalbert commented on release-gh/action.yml
>        submodules: true
```suggestion
      submodules: true
      show-progress: false
```

2024-02-13 05:01 UTC, dhalbert commented on release-gh/action.yml
>        repository: adafruit/actions-ci-circuitpython-libs
```suggestion
      show-progress: false
      repository: adafruit/actions-ci-circuitpython-libs
```

2024-02-13 05:01 UTC, dhalbert commented on release-pypi/action.yml
> +  - uses: actions/checkout@v4
```suggestion
  - uses: actions/checkout@v4
    with:
        show-progress: false
```

2024-02-13 17:27 UTC, dhalbert approved these changes
Thanks, let's try it!

2024-02-13 17:27 UTC, merged